library(lpSolve)
obj = c(3,2)
mat = matrix(c(-1,-1,1,1,1,2,0,1),ncol=2,byrow=TRUE)
dir = c("<=","<=","<=","<=")
rhs = c(-1,7,10,3)
ps = lp("max",obj,mat,dir,rhs)
dir_2 = c(">=",">=")
ds = lp("min",rhs,t(mat),dir_2,obj)
cat("Primal Solution")
cat("Optimal Solution :",ps$solution[1:length(obj)])
cat("Optimal Value :",ps$objval)
cat("Dual Solution")
cat("Optimal Solution :",ds$solution[1:length(rhs)])
cat("Optimal Value :",ds$objval)