library(lpSolve)
obj = c(2,2)
mat = matrix(c(2,4,1,2,2,1),ncol=2,byrow=TRUE)
dir = c(">=",">=",">=")
rhs = c(1,1,1)
ps = lp("min",obj,mat,dir,rhs)
dir_2 = c("<=","<=")
ds = lp("max",rhs,t(mat),dir_2,obj)
cat("Primal Solution")
cat("Optimal Solution :",ps$solution[1:length(obj)])
cat("Optimal Value :",ps$objval)
cat("Dual Solution")
cat("Optimal Solution :",ds$solution[1:length(rhs)])
cat("Optimal Value :",ds$objval)